vote/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #/
    url(r'^$', views.landing, name='landing'),
    #home/ --homepage
    url(r'^home/$', views.home, name='home'),
    #mypolls/ -- show polls
    url(r'^mypolls/$', views.PollList.as_view(), name='poll-list'),
    #poll/details/<pk>
    url(r'^poll/details/(?P<pk>[0-9]+)/$', views.PollDetails.as_view(), name='poll-details'),
    #create/
    url(r'^create/$', views.create, name='create'),
    #vote/<question_id>/
    url(r'^vote/(?P<question_id>[0-9]+)/$', views.vote, name='vote1'),
    #poll/results/<pk>
    url(r'^poll/results/(?P<pk>[0-9]+)/$', views.PollResults.as_view(), name='results'),
    #poll/delete/<pk>
    url(r'^poll/delete/(?P<pk>[0-9]+)/$', views.PollDelete.as_view(), name='poll-delete'),
    #pollurl/
    url(r'^pollurl/(?P<id>[0-9]+)/$', views.pollurl, name='pollurl'),
    #password/
    url(r'^password/$', views.change_password, name='password-change')
]

vote_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from vote import views as core_views
from django.contrib.auth import views as auth_views
from vote import views
from vote.forms import LoginForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('vote.urls', namespace='vote')),
]

#auth urls
urlpatterns += [
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^accounts/login/$', auth_views.login,{'template_name':'registration/login.html', 'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

vote/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey('auth.User', related_name='questions', on_delete=models.CASCADE)
    ip = models.CharField(max_length=200)
    
    def __str__(self):
        return self.question_text
        

class Choices(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    ip = models.CharField(max_length=200)
    owner = models.ForeignKey('auth.User', related_name='choices', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.choice_text
    

vote/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.models import User



class PollForm(forms.Form):
    question_text = forms.CharField(label='Question', max_length=200,
                    widget = forms.TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'Question',
                    })
    )
    choice_text = forms.CharField(label='Choice1', max_length=200,
                    widget = forms.TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'First choice..'
                    })
    )
    choice_text2 = forms.CharField(label='Choice2', max_length=200,
                    widget = forms.TextInput(attrs={
                        'class': 'form-control',
                        'placeholder': 'Second choice..'
                    })
    )
    

    def clean(self):
        cleaned_data = super(PollForm, self).clean()
        question_text = cleaned_data.get('question_text')
        choice_text = cleaned_data.get('choice_text')
        choice_text2= cleaned_data.get('choice_text2')
        
        if not question_text and not choice_text and not choice_text2:
            raise forms.ValidationError('You have to write something!')


# class UserCreateForm(UserCreationForm):
#     def __init__(self, *args, **kwargs):
#         super(UserCreateForm, self).__init__(*args, **kwargs)

#         for fieldname in ['username', 'password1', 'password2']:
#             self.fields[fieldname].help_text = None


#customized sign up form
class UserCreateForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    username = forms.CharField(label=_("Username"),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        })
        )
    
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        }))
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Confirm Password',
        }))

    class Meta:
        model = User
        fields = ("username",)

        


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

#customized login form
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label = _("Username"),
        widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username',
        })
    )
    password = forms.CharField(
        label = _("Password"),
        widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        })
    )


class PasswordChange(PasswordChangeForm):
    def __init__(self, user, *args, **kwargs):
        super(PasswordChange, self).__init__(user, *args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control',
                                                         'placeholder': 'Current Password'})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control',
                                                          'placeholder': 'New Password'})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control',
                                                          'placeholder': 'Confirm Password'})

vote/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.views.generic.edit import CreateView, DeleteView
from .models import Question, Choices
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .forms import PollForm, UserCreateForm, PasswordChange
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin





def landing(request):
    return render(request, 'vote/landing.html')


@login_required
def home(request):
    return render(request, 'vote/home.html')

@login_required
def pollurl(request, id):
    questions = Question.objects.get(id=id)
    context = {
        'questions': questions
    }
    return render(request, 'vote/pollurl.html', context)
    

def signup(request):
    if (request.method == 'POST'):
        form = UserCreateForm(request.POST)
        if (form.is_valid()):
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('vote:home')
    else:
        form = UserCreateForm()
    return render(request, 'registration/signup.html', {'form': form})
    
    
class PollList(LoginRequiredMixin, ListView):
    model = Question
    context_object_name = 'questions'
    
    def get_queryset(self):
        return Question.objects.filter(owner=self.request.user)

class PollDetails(DetailView):
    model = Question
    template_name = 'vote/poll_details.html'
    
    # def get_queryset(self):
    #     return Question.objects.filter(owner=self.request.user)


class PollResults(DetailView):
    model = Question
    template_name = 'vote/results.html'

    # def get_queryset(self):
    #     return Question.objects.filter(owner=self.request.user)


class PollDelete(LoginRequiredMixin, DeleteView):
    model = Question
    success_url = reverse_lazy('vote:poll-list')


@login_required        
def create(request):
    
    if (request.method == 'POST'):
        form = PollForm(request.POST)
        
        if (form.is_valid()):
            question = form.cleaned_data.get('question_text')
            choice1 = form.cleaned_data.get('choice_text')
            choice2 = form.cleaned_data.get('choice_text2')
            
            
            q = Question.objects.create(question_text=question, owner=request.user)
            q1 = Question.objects.get(id=q.id)
            
            
            q1.choices_set.create(choice_text=choice1, owner=request.user)
            q1.choices_set.create(choice_text=choice2, owner=request.user)

            
            return redirect('vote:pollurl', q.id)
    else:
        form = PollForm()
    return render(request, 'forms/poll_form.html', {'form': form})
            


def vote(request, question_id):
    useragent = request.META['REMOTE_ADDR']
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choices_set.get(pk=request.POST['choice'])
    except (KeyError, Choices.DoesNotExist):
        return render(request, 'vote/poll_details.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    if(question.ip == useragent):
        return render(request, 'vote/voted_once.html')
    else:
        selected_choice.votes += 1
        question.ip = useragent
        selected_choice.save()
        question.save()
        
    return redirect('vote:results', question.id)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChange(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('vote:home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChange(request.user)
    return render(request, 'forms/change_password.html', {
        'form': form
    })

vote/templates/base/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}

<head>
  <title>Vote app</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
    crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'vote/main.css' %}">
  <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
  <script src="{% static 'vote/main.js' %}"></script>
</head>

<body>
  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Pollify</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'vote:home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'vote:poll-list' %}">My Polls
            <span class="sr-only">(current)</span>
          </a>
        </li>
      </ul>
      <div class="row text-center">
          {% if user.is_authenticated %}
            <div class="col-sm-4">
                <p class="set-right">{{ user.get_username }}</p>
            </div>
             <div class="col-sm-2">
                <a href="{% url 'vote:password-change' %}">
                    <i class="fa fa-cog" aria-hidden="true"></i>
                </a>
             </div>
             <div class="col-sm-6">
             <a class=" set-right" href="{% url 'logout' %}">Logout</a>
             </div>
           {% endif %}
      </div>
    </div>
  </nav>

  {% block content %} {% endblock %}


</body>

</html>

vote/templates/base/base2.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    <head>
        <title>Vote app</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" 
        integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" 
        crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'vote/main.css' %}">        
    </head>
    <body>

        {% block content %}
        {% endblock %}
        
        
        <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
        <script src="{% static 'vote/main.js' %}"></script>        
    </body>
</html>